# Generated by Django 3.1.2 on 2020-10-14 21:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ttkom', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('date_comment', models.DateTimeField(auto_now_add=True)),
                ('fk_author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('fk_post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ttkom.post')),
                ('likes', models.ManyToManyField(related_name='blog_comment', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
